# Pandas
Pandas is a Python library used for working with data sets.  
It has functions for analyzing, cleaning, exploring, and manipulating data.  
The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

### Why Use Pandas?
1. Pandas allows us to analyze big data and make conclusions based on statistical theories.

2. Pandas can clean messy data sets, and make them readable and relevant.

3. Relevant data is very important in data science.

In [1]:
# Installation of Pandas
    # pip install pandas
# Once Pandas is installed, import it in your applications by adding the "import" keyword:
import pandas as pd

In [3]:
alpha = pd.Series(['A','B','C','D'])  # Uses pd.Series() to convert the array into a Pandas Series.
alpha

0    A
1    B
2    C
3    D
dtype: object

In [4]:
# in python , simply we do like:
data=['A','B','C','D']

for idx, val in enumerate(data):
    print(f'{idx}  {val}')
print(f'dtype: {type(val)}')

0  A
1  B
2  C
3  D
dtype: <class 'str'>

In [9]:
# multiple list data:
personal_details = pd.DataFrame([
    ['Ram',30,'KTM','Bachelor'],
    ['Lochan',25,'DNG','Bachelor'],
    ['Bibke',20,'BKT','High Scool'],
    ['Roshan',29,'LAL','Master'],
    ['Shyma',20,'POK','Bachelor']
])  # row is replace by using index and row is not take to name

print(personal_details)

        0   1    2           3
0     Ram  30  KTM    Bachelor
1  Lochan  25  DNG    Bachelor
2   Bibke  20  BKT  High Scool
3  Roshan  29  LAL      Master
4   Shyma  20  POK    Bachelor

In [10]:
personal_details = pd.DataFrame([
    ['Ram',30,'KTM','Bachelor'],
    ['Lochan',25,'DNG','Bachelor'],
    ['Bibke',20,'BKT','High Scool'],
    ['Roshan',29,'LAL','Master'],
    ['Shyma',20,'POK','Bachelor']
],columns=['Name','Age','Address','Qualification'],
                                index=['A','B','C','D','E']) 
#columns is used for nameing the columns 
# row is replace by using index and row is not take to name

print(personal_details)

     Name  Age Address Qualification
A     Ram   30     KTM      Bachelor
B  Lochan   25     DNG      Bachelor
C   Bibke   20     BKT    High Scool
D  Roshan   29     LAL        Master
E   Shyma   20     POK      Bachelor

In [13]:
# slicing
alpha[1:3]  #simple slicing

1    B
2    C
dtype: object

In [14]:
personal_details[1:3]  # sicling with index

     Name  Age Address Qualification
B  Lochan   25     DNG      Bachelor
C   Bibke   20     BKT    High Scool

In [15]:
#slicing with index name
personal_details['B':'D']

     Name  Age Address Qualification
B  Lochan   25     DNG      Bachelor
C   Bibke   20     BKT    High Scool
D  Roshan   29     LAL        Master

# .loc[]
.loc[] is label-based indexing.  
It selects data using the row labels (index names) and column labels (column names).   
It is used to slice the data using alphabet index  
### Syntax
    df.loc[row_label, column_label]

In [16]:
personal_details

     Name  Age Address Qualification
A     Ram   30     KTM      Bachelor
B  Lochan   25     DNG      Bachelor
C   Bibke   20     BKT    High Scool
D  Roshan   29     LAL        Master
E   Shyma   20     POK      Bachelor

In [20]:
#Selecting the single row
personal_details.loc['A']

Name                  Ram
Age                    30
Address               KTM
Qualification    Bachelor
Name: A, dtype: object

In [23]:
# Selecting multiple rows
personal_details.loc['A':'D']

     Name  Age Address Qualification
A     Ram   30     KTM      Bachelor
B  Lochan   25     DNG      Bachelor
C   Bibke   20     BKT    High Scool
D  Roshan   29     LAL        Master

In [25]:

# Selecting a Single Value
personal_details.loc['B':'D','Name']

B    Lochan
C     Bibke
D    Roshan
Name: Name, dtype: object

In [28]:
# Selecting multiple cloumns
personal_details.loc[:,['Name','Address']]  # : means all rows.
                                            # select only Name and Address

     Name Address
A     Ram     KTM
B  Lochan     DNG
C   Bibke     BKT
D  Roshan     LAL
E   Shyma     POK

In [29]:
# With .loc, the ending index is INCLUDED.
personal_details.loc['B':'D']

     Name  Age Address Qualification
B  Lochan   25     DNG      Bachelor
C   Bibke   20     BKT    High Scool
D  Roshan   29     LAL        Master

In [30]:
# Boolean Filtering with .loc
personal_details.loc[personal_details['Age']>25]

     Name  Age Address Qualification
A     Ram   30     KTM      Bachelor
D  Roshan   29     LAL        Master

In [31]:
personal_details[['Name','Address']]  # for pandas
#select name, address form personal_details);   # for SQL

     Name Address
A     Ram     KTM
B  Lochan     DNG
C   Bibke     BKT
D  Roshan     LAL
E   Shyma     POK

In [32]:
personal_details.loc[
    ['B','D'],
    ["Name","Address"]
]

     Name Address
B  Lochan     DNG
D  Roshan     LAL

# .iloc[]
.iloc[] is integer position-based indexing.   
It selects data using the numerical position of rows and columns.   
ILoc -> Integer Location -> used to slice data using numeric index

### Syntax
    df.iloc[row_position, column_position]

In [33]:
personal_details

     Name  Age Address Qualification
A     Ram   30     KTM      Bachelor
B  Lochan   25     DNG      Bachelor
C   Bibke   20     BKT    High Scool
D  Roshan   29     LAL        Master
E   Shyma   20     POK      Bachelor

In [34]:
#Selecting first row
personal_details.iloc[0]

Name                  Ram
Age                    30
Address               KTM
Qualification    Bachelor
Name: A, dtype: object

In [36]:
personal_details.iloc[1]

Name               Lochan
Age                    25
Address               DNG
Qualification    Bachelor
Name: B, dtype: object

In [47]:
# selecting single value
personal_details.iloc[1,0]

'Lochan'

In [50]:
personal_details.iloc[1:3,0:4]

     Name  Age Address Qualification
B  Lochan   25     DNG      Bachelor
C   Bibke   20     BKT    High Scool

In [54]:
personal_details.iloc[
        [1,3],
        [1,2]
    ]

   Age Address
B   25     DNG
D   29     LAL

In [55]:
#to check information of data
personal_details.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           5 non-null      object
 1   Age            5 non-null      int64
 2   Address        5 non-null      object
 3   Qualification  5 non-null      object
dtypes: int64(1), object(3)
memory usage: 372.0+ bytes

In [56]:
personal_details.ndim

2

In [57]:
personal_details.size

20

In [58]:
personal_details.shape

(5, 4)