# Conditional Filtering

Conditional Filtering means selecting only those rows from a DataFrame that satisfy a specific condition.

Think of it like applying a filter in Excel:

"Show me only students whose marks are greater than 80."

Instead of viewing all data, you view only the records that match your condition.

In [1]:
# Step 1: Importing pandas
import pandas as pd

# Step 2 : Eeading for csv File
emp=pd.read_csv('Dataset/Employees.csv')
emp

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

# Data Types in a DataFrame

A data type defines the kind of values that can be stored in a column.

### Integer (int)

Stores whole numbers without decimal points.

Examples:

1. Age
2. Number of students
3. Quantity sold

Characteristics:

1. Used for counting.
2. Takes less memory than floating-point numbers.
### Float (float)

Stores numerical values with decimal points.

Examples:

Salary
Height
Weight
Temperature

Characteristics:

Used when precision is required.
Represents continuous measurements.
### String (str or object)

Stores textual data.

Examples:

1. Name
2. Address
3. Country
4. Department

Characteristics:

1. Used for descriptive information.
2. Cannot be used directly for mathematical calculations.
### Boolean (bool)

Stores logical values.

Possible values:

1. True
2. False

Examples:

* Is Student?
* Is Active?
* Is Employed?

Characteristics:

* Frequently used in filtering and conditional operations.
### Datetime

Stores date and time information.

Examples:

* Birth Date
* Joining Date
* Transaction Date

Characteristics:

* Enables time-based analysis.
* Useful for trend and forecasting analysis.
### Complex Numbers

Stores numbers having real and imaginary parts.

Example:

* 3 + 4j

Characteristics:

* Mostly used in scientific and engineering computations.
* Rarely used in business datasets.
### Missing Values (NaN/None)

Represents unavailable or unknown information.

Examples:

* Name      Salary
* Ram       50000
* Hari      NaN

Characteristics:

* Indicates incomplete data.
* Requires special handling during data cleaning.

# Types of Data in a Dataset

Data can be broadly divided into two major categories.

# A. Numerical Data (Quantitative Data)

Numerical data represents measurable quantities and can be used for mathematical calculations.

Examples:

* Age
* Salary
* Marks
* Height

Numerical data is further divided into:

### Discrete Data

Discrete data consists of countable values, whole number, unique number, must be in range

Examples:

* Number of students in a class
* Number of cars owned
* Number of employees

Characteristics:

* Usually whole numbers.
* Cannot have intermediate values.

Example:

    Students = 25

You cannot have:

    Students = 25.5
### Continuous Data

Continuous data can take any value in range or not in range,can be whole number or decimal valuese.

Examples:

* Height
* Weight
* Temperature
* Time
* Price
* Sales
* Marks
* Salary

Characteristics:

* Can contain decimal values.
* Obtained through measurement.

Example:

    Height = 170.45 cm
# B. Categorical Data (Qualitative Data)

Categorical data represents categories or labels rather than numerical measurements.

Examples:

* Gender
* Department
* Country
* Product Type

Categorical data is divided into:

### Nominal Data

Nominal data consists of categories without any natural order.

Examples:
* Blood Group
* Color
* Gender
* Caste
* Race 

Characteristics:

* Categories are different but not ranked.
* Mathematical operations are not meaningful.
### Ordinal Data

Ordinal data consists of categories that have a meaningful order.

Examples:

* Grade
* Food

Characteristics:

* Ranking exists.
* The exact difference between categories is unknown.

Numeric case:
------------------
mean -> if our data is in range -> Best when no significant outliers exist.

median -> if our data is not in range -> Best when data contains outliers or is skewed.


Numeric and Categorical both case:
-----------------------
mode -> Highest number of occurrence value ->

custom record -> A custom record generally refers to a specific observation or row in a dataset that is selected based on business requirements or custom conditions.

# Outliers

An outlier is an observation that differs significantly from the rest of the data.

### Definition:

A value that lies unusually far away from other observations in a dataset.

### Effects of Outliers

* Distort the mean.
* Increase variance.
* Affect statistical models.
* Lead to incorrect conclusions.

### Why Are Outliers Important?

Before performing analysis or building machine learning models, outliers must be identified because they can:

* Reduce model accuracy.
* Misrepresent trends.
* Influence predictions.

Common detection methods include:
* Box Plots
* Interquartile Range (IQR)
* Z-Score Method

In [2]:
# find all the details of employeee who earns more than 7000.
emp_salary= emp['SALARY']>7000
emp[emp_salary]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,8/17/2002,FI_MGR,12008,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,8/16/2002,FI_ACCOUNT,9000,NaN,108.0,100.0
10,110,John,Chen,JCHEN,515.124.4269,9/28/2005,FI_ACCOUNT,8200,NaN,108.0,100.0
11,111,Ismael,Sciarra,ISCIARRA,515.124.4369,9/30/2005,FI_ACCOUNT,7700,NaN,108.0,100.0
12,112,Jose Manuel,Urman,JMURMAN,515.124.4469,3/7/2006,FI_ACCOUNT,7800,NaN,108.0,100.0
14,114,Den,Raphaely,DRAPHEAL,515.127.4561,12/7/2002,PU_MAN,11000,NaN,100.0,30.0
20,120,Matthew,Weiss,MWEISS,650.123.1234,7/18/2004,ST_MAN,8000,NaN,100.0,50.0
21,121,Adam,Fripp,AFRIPP,650.123.2234,4/10/2005,ST_MAN,8200,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,5/1/2003,ST_MAN,7900,NaN,100.0,50.0
45,145,John,Russell,JRUSSEL,011.44.1344.429268,10/1/2004,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,1/5/2005,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,3/10/2005,SA_MAN,12000,0.30,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,10/15/2007,SA_MAN,11000,0.30,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,1/29/2008,SA_MAN,10500,0.20,100.0,80.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,1/30/2005,SA_REP,10000,0.30,145.0,80.0
51,151,David,Bernstein,DBERNSTE,011.44.1344.345268,3/24/2005,SA_REP,9500,0.25,145.0,80.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,8/20/2005,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,3/30/2006,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,12/9/2006,SA_REP,7500,0.20,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,1/30/2004,SA_REP,10000,0.35,146.0,80.0
57,157,Patrick,Sully,PSULLY,011.44.1345.929268,3/4/2004,SA_REP,9500,0.35,146.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,8/1/2004,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,3/10/2005,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,12/15/2005,SA_REP,7500,0.30,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,11/11/2005,SA_REP,10500,0.25,147.0,80.0
63,163,Danielle,Greene,DGREENE,011.44.1346.229268,3/19/2007,SA_REP,9500,0.15,147.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,1/24/2008,SA_REP,7200,0.10,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,3/11/2005,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,3/23/2006,SA_REP,10000,0.20,148.0,80.0
70,170,Tayler,Fox,TFOX,011.44.1343.729268,1/24/2006,SA_REP,9600,0.20,148.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2/23/2007,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,3/24/2007,SA_REP,7300,0.15,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,5/11/2004,SA_REP,11000,0.30,149.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,3/19/2005,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,3/24/2006,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,4/23/2006,SA_REP,8400,0.20,149.0,80.0
101,201,Michael,Hartstein,MHARTSTE,515.123.5555,2/17/2004,MK_MAN,13000,NaN,100.0,20.0
104,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

### Error comes like

In [16]:
# find details of employee who earns more  in the range of 6000 and 9000
emp_sal_range =emp['SALARY']>=6000 and emp['SALARY'] <=9000

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [4]:
emp_sal_range =emp['SALARY']>=6000 & emp['SALARY'] <=9000

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [5]:
emp_sal_range =(emp['SALARY']>=6000) & (emp['SALARY'] <=9000)  
emp[emp_sal_range]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,8/16/2002,FI_ACCOUNT,9000,NaN,108.0,100.0
10,110,John,Chen,JCHEN,515.124.4269,9/28/2005,FI_ACCOUNT,8200,NaN,108.0,100.0
11,111,Ismael,Sciarra,ISCIARRA,515.124.4369,9/30/2005,FI_ACCOUNT,7700,NaN,108.0,100.0
12,112,Jose Manuel,Urman,JMURMAN,515.124.4469,3/7/2006,FI_ACCOUNT,7800,NaN,108.0,100.0
13,113,Luis,Popp,LPOPP,515.124.4567,12/7/2007,FI_ACCOUNT,6900,NaN,108.0,100.0
20,120,Matthew,Weiss,MWEISS,650.123.1234,7/18/2004,ST_MAN,8000,NaN,100.0,50.0
21,121,Adam,Fripp,AFRIPP,650.123.2234,4/10/2005,ST_MAN,8200,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,5/1/2003,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10/10/2005,ST_MAN,6500,NaN,100.0,50.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,8/20/2005,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,3/30/2006,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,12/9/2006,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,11/23/2007,SA_REP,7000,0.15,145.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,8/1/2004,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,3/10/2005,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,12/15/2005,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,11/3/2006,SA_REP,7000,0.25,146.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,1/24/2008,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2/23/2008,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,3/24/2008,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,4/21/2008,SA_REP,6200,0.10,147.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2/23/2007,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,3/24/2007,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,4/21/2008,SA_REP,6100,0.10,148.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,3/19/2005,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,3/24/2006,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,4/23/2006,SA_REP,8400,0.20,149.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,5/24/2007,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,1/4/2008,SA_REP,6200,0.10,149.0,80.0
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [7]:
# between() function has inclusive dataset

emp_sal_between = emp['SALARY'].between(6000,9000)  
emp[emp_sal_between]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,8/16/2002,FI_ACCOUNT,9000,NaN,108.0,100.0
10,110,John,Chen,JCHEN,515.124.4269,9/28/2005,FI_ACCOUNT,8200,NaN,108.0,100.0
11,111,Ismael,Sciarra,ISCIARRA,515.124.4369,9/30/2005,FI_ACCOUNT,7700,NaN,108.0,100.0
12,112,Jose Manuel,Urman,JMURMAN,515.124.4469,3/7/2006,FI_ACCOUNT,7800,NaN,108.0,100.0
13,113,Luis,Popp,LPOPP,515.124.4567,12/7/2007,FI_ACCOUNT,6900,NaN,108.0,100.0
20,120,Matthew,Weiss,MWEISS,650.123.1234,7/18/2004,ST_MAN,8000,NaN,100.0,50.0
21,121,Adam,Fripp,AFRIPP,650.123.2234,4/10/2005,ST_MAN,8200,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,5/1/2003,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10/10/2005,ST_MAN,6500,NaN,100.0,50.0
52,152,Peter,Hall,PHALL,011.44.1344.478968,8/20/2005,SA_REP,9000,0.25,145.0,80.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,3/30/2006,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,12/9/2006,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,11/23/2007,SA_REP,7000,0.15,145.0,80.0
58,158,Allan,McEwen,AMCEWEN,011.44.1345.829268,8/1/2004,SA_REP,9000,0.35,146.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,3/10/2005,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,12/15/2005,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,11/3/2006,SA_REP,7000,0.25,146.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,1/24/2008,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2/23/2008,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,3/24/2008,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,4/21/2008,SA_REP,6200,0.10,147.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2/23/2007,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,3/24/2007,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,4/21/2008,SA_REP,6100,0.10,148.0,80.0
75,175,Alyssa,Hutton,AHUTTON,011.44.1644.429266,3/19/2005,SA_REP,8800,0.25,149.0,80.0
76,176,Jonathon,Taylor,JTAYLOR,011.44.1644.429265,3/24/2006,SA_REP,8600,0.20,149.0,80.0
77,177,Jack,Livingston,JLIVINGS,011.44.1644.429264,4/23/2006,SA_REP,8400,0.20,149.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,5/24/2007,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,1/4/2008,SA_REP,6200,0.10,149.0,80.0
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [8]:
# Find the details of employee who works under IT_PRG and ST_MAN.
 # In categorical use 'or' or ' | '  
emp_job= emp[(emp['JOB_ID'] =='IT_PROG') | (emp['JOB_ID'] =='ST_MAN')]
emp_job

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2/5/2006,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2/7/2007,IT_PROG,4200,NaN,103.0,60.0
20,120,Matthew,Weiss,MWEISS,650.123.1234,7/18/2004,ST_MAN,8000,NaN,100.0,50.0
21,121,Adam,Fripp,AFRIPP,650.123.2234,4/10/2005,ST_MAN,8200,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,5/1/2003,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10/10/2005,ST_MAN,6500,NaN,100.0,50.0
24,124,Kevin,Mourgos,KMOURGOS,650.123.5234,11/16/2007,ST_MAN,5800,NaN,100.0,50.0

In [14]:
# Find the details of employee who works under IT_PRG and ST_MAN.
emp_job_isin= emp[emp['JOB_ID'].isin(['IT_PROG','ST_MAN'])] 
# The .isin()  used for filtering and selecting data based on specified values.
emp_job_isin

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2/5/2006,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2/7/2007,IT_PROG,4200,NaN,103.0,60.0
20,120,Matthew,Weiss,MWEISS,650.123.1234,7/18/2004,ST_MAN,8000,NaN,100.0,50.0
21,121,Adam,Fripp,AFRIPP,650.123.2234,4/10/2005,ST_MAN,8200,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,5/1/2003,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10/10/2005,ST_MAN,6500,NaN,100.0,50.0
24,124,Kevin,Mourgos,KMOURGOS,650.123.5234,11/16/2007,ST_MAN,5800,NaN,100.0,50.0

In [10]:
# Find details of employee who earn between 9000 and 6000 and must be working on job ST_MAN
emp_ear_job=emp[emp['SALARY'].between(6000,9000) & (emp['JOB_ID'] =='ST_MAN') ]
emp_ear_job

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
20,120,Matthew,Weiss,MWEISS,650.123.1234,7/18/2004,ST_MAN,8000,NaN,100.0,50.0
21,121,Adam,Fripp,AFRIPP,650.123.2234,4/10/2005,ST_MAN,8200,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,5/1/2003,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10/10/2005,ST_MAN,6500,NaN,100.0,50.0

In [11]:
# In maximum 5 lakhs dataset use between but range use for its less time computation
emp_ear_job=emp[((emp['SALARY']>=6000) & (emp['SALARY'] <=9000)) & (emp['JOB_ID'] =='ST_MAN') ]
emp_ear_job

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
20,120,Matthew,Weiss,MWEISS,650.123.1234,7/18/2004,ST_MAN,8000,NaN,100.0,50.0
21,121,Adam,Fripp,AFRIPP,650.123.2234,4/10/2005,ST_MAN,8200,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,5/1/2003,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10/10/2005,ST_MAN,6500,NaN,100.0,50.0

In [12]:
emp_st_man=emp[emp['JOB_ID']=='ST_MAN']
emp_st_man['SALARY']

20    8000
21    8200
22    7900
23    6500
24    5800
Name: SALARY, dtype: int64

In [15]:
emp_st_man=emp[emp['JOB_ID']=='ST_MAN']['SALARY'] # use this while doing hypothesis test
emp_st_man

20    8000
21    8200
22    7900
23    6500
24    5800
Name: SALARY, dtype: int64